services:
  db:
    image: mariadb:10.7
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: testdb
    volumes:
      - db-data:/var/lib/mysql
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
    environment:
      DATABASE_PASSWORD: password
    ports:
      - "3000:3000"
    volumes:
      - .:/samplerails
    tty: true
volumes:
  db-data: